//taken when the image is 917x688
import { type Section } from "@/app/utils/types"


const sectionCoords = [
  {
    upperLeft: [115, 126],
    lowerRight: [220, 223]
  }
]

export const sections: Section[] = [
  {
    displayName: 'Shipping Containers',
    date: '27/01/2024',
    bgColour: '#08212b',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-sm',
    url: 'https://shippingcontainers.vercel.app/',
    target: '_blank',
    leftShift: 12.6,
    topShift: 18.3,
    width: 11.8,
    height: 13.8,
  },
  {
    displayName: 'Copy Blocks',
    date: '28/01/2024',
    bgColour: '#0f2d38',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-base',
    url: 'https://copyblocks.vercel.app/',
    target: '_blank',
    leftShift: 24.5,
    topShift: 19.3,
    width: 13,
    height: 13.8
  },
  {
    displayName: 'Context Translate',
    date: '29/01/2024',
    bgColour: '#1a3a47',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-base',
    url: 'https://context-translate.vercel.app/',
    target: '_blank',
    leftShift: 37.6,
    topShift: 20.3,
    width: 13.3,
    height: 13.5
  },
  {
    displayName: 'Metropolitan Art',
    date: '30/01/2024',
    bgColour: '#274754',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-xs',
    url: 'https://metropolitan-art.vercel.app/',
    target: '_blank',
    leftShift: 51.4,
    topShift: 20.8,
    width: 10,
    height: 13.3
  },
  {
    displayName: 'TfL Locate',
    date: '31/01/2024',
    bgColour: '#526b75',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-base',
    url: 'https://tfl-locate.vercel.app/',
    target: '_blank',
    leftShift: 61.8,
    topShift: 21.8,
    width: 11.8,
    height: 12.5
  },
  {
    displayName: 'SVG Pattern Generator',
    date: '01/02/2024',
    bgColour: '#79919a',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-sm',
    url: 'https://pattern-generator-one.vercel.app/',
    target: '_blank',
    leftShift: 73.8,
    topShift: 22.3,
    width: 14,
    height: 12.3
  },
  {
    displayName: 'Run counter',
    date: '02/02/2024',
    bgColour: '#0a4841',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-base',
    url: 'https://fun-run-counter.vercel.app/',
    target: '_blank',
    leftShift: 13,
    topShift: 32.3,
    width: 11,
    height: 11.8
  },
  {
    displayName: 'Cookie Clicker',
    date: '03/02/2024',
    bgColour: '#12635a',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-sm',
    url: 'https://cookies-cookie-clicker.vercel.app/',
    target: '_blank',
    leftShift: 24.3,
    topShift: 33.3,
    width: 13.2,
    height: 10
  },
  {
    displayName: 'Caesar Cipher',
    date: '04/02/2024',
    bgColour: '#1e8075',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-sm',
    url: 'https://cookies-caesar-cipher.vercel.app/',
    target: '_blank',
    leftShift:38,
    topShift: 34,
    width: 13.2,
    height: 10
  },
  {
    displayName: 'Scroll Animations',
    date: '05/02/2024',
    bgColour: '#2a9d90',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-xs',
    url: 'https://new-spacex.vercel.app/',
    target: '_blank',
    leftShift: 51.8,
    topShift: 34.5,
    width: 9,
    height: 10
  },
  {
    displayName: 'AND Gate',
    date: '06/02/2024',
    bgColour: '#3cc8b8',
    textColour: 'black',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-base',
    url: 'https://and-gate.vercel.app/',
    target: '_blank',
    leftShift: 61.2,
    topShift: 34.5,
    width: 11.5,
    height: 11
  },
  {
    displayName: 'Visited Countries',
    date: '07/02/2024',
    bgColour: '#69d8cb',
    textColour: 'black',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-sm',
    url: 'https://visited-countries-blue.vercel.app/',
    target: '_blank',
    leftShift: 73,
    topShift: 35,
    width: 14.8,
    height: 11.6
  },
  {
    displayName: 'React Context Example',
    date: '08/02/2024',
    bgColour: '#76590f',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-xs',
    url: 'https://react-context-example-hazel.vercel.app/',
    target: '_blank',
    leftShift: 13.3,
    topShift: 44.3,
    width: 11,
    height: 12
  },
  {
    displayName: 'Single Hue Palette Generator',
    date: '09/02/2024',
    bgColour: '#af861d',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-xs',
    url: 'https://single-hue-palette.vercel.app/',
    target: '_blank',
    leftShift: 24.6,
    topShift: 44,
    width: 12.8,
    height: 12.5
  },
  {
    displayName: 'Redux Example',
    date: '10/02/2024',
    bgColour: '#dcac32',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-base',
    url: 'https://redux-example-swart.vercel.app/',
    target: '_blank',
    leftShift: 38,
    topShift: 44.3,
    width: 12.8,
    height: 12.5
  },
  {
    displayName: 'Social Media for cows',
    date: '11/02/2024',
    bgColour: '#e8c468',
    textColour: 'black',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-xs',
    url: 'https://youmoo.vercel.app/',
    target: '_blank',
    leftShift: 51,
    topShift: 45,
    width: 9,
    height: 12.5
  },
  {
    displayName: 'SpaceX Landing Page',
    date: '12/02/2024',
    bgColour: '#efd185',
    textColour: 'black',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-xs',
    url: 'https://new-spacex.vercel.app/',
    target: '_blank',
    leftShift: 60.3,
    topShift: 45.8,
    width: 11.5,
    height: 12.2
  },
  {
    displayName: 'Pixel Clock',
    date: '13/02/2024',
    bgColour: '#f5dea3',
    textColour: 'black',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-base',
    url: 'https://pixel-clock.vercel.app/',
    target: '_blank',
    leftShift: 72.3,
    topShift: 46.8,
    width: 15.5,
    height: 12
  },
  {
    displayName: 'Daisy Petals',
    date: '14/02/2024',
    bgColour: '#813f08',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-base',
    url: 'https://daisy-petals.vercel.app/',
    target: '_blank',
    leftShift: 13.3,
    topShift: 57,
    width: 10.8,
    height: 12.8
  },
  {
    displayName: 'Weird Calendar',
    date: '15/02/2024',
    bgColour: '#be5d0e',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-sm',
    url: 'https://weird-calendar.vercel.app/',
    target: '_blank',
    leftShift: 24.7,
    topShift: 56.9,
    width: 12.8,
    height: 12.8
  },
  {
    displayName: 'Book Stack',
    date: '16/02/2024',
    bgColour: '#ed8026',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-base',
    url: 'https://book-stack-ten.vercel.app/',
    target: '_blank',
    leftShift: 37.8,
    topShift: 57.1,
    width: 13,
    height: 12.9
  },
  {
    displayName: 'Traditional Scoreboard',
    date: '17/02/2024',
    bgColour: '#f4a462',
    textColour: 'black',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-xs',
    url: 'https://traditional-scoreboard.vercel.app/',
    target: '_blank',
    leftShift: 51,
    topShift: 58,
    width: 9.3,
    height: 12.5
  },
  {
    displayName: 'Office Episode Generator',
    date: '18/02/2024',
    bgColour: '#f8b782',
    textColour: 'black',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-xs',
    url: 'https://office-episode.vercel.app//',
    target: '_blank',
    leftShift: 60.5,
    topShift: 58.3,
    width: 11.7,
    height: 12.5
  },
  {
    displayName: 'Zustand Example',
    date: '19/02/2024',
    bgColour: '#fac79e',
    textColour: 'black',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-xs',
    url: 'https://zustand-example-ten.vercel.app/',
    target: '_blank',
    leftShift: 72.5,
    topShift: 59.1,
    width: 14.9,
    height: 12
  },
  {
    displayName: 'Top Fives',
    date: '20/02/2024',
    bgColour: '#6f1f0b',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-base',
    url: 'https://top-five-lists.vercel.app/',
    target: '_blank',
    leftShift: 13.3,
    topShift: 70.2,
    width: 10.9,
    height: 11.3
  },
  {
    displayName: 'Top Fives',
    date: '20/02/2024',
    bgColour: '#6f1f0b',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-base',
    url: 'https://top-five-lists.vercel.app/',
    target: '_blank',
    leftShift: 13.3,
    topShift: 70.2,
    width: 10.9,
    height: 11.3
  },
  {
    displayName: 'Decimal to Binary',
    date: '21/02/2024',
    bgColour: '#a63317',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-xs',
    url: 'https://binary-converter-ebon.vercel.app/',
    target: '_blank',
    leftShift: 24.7,
    topShift: 70.2,
    width: 12.8,
    height: 11.3
  },
  {
    displayName: 'Jotai Example',
    date: '22/02/2024',
    bgColour: '#db451f',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-xs',
    url: 'https://jotai-example-tau.vercel.app/',
    target: '_blank',
    leftShift: 37.8,
    topShift: 70.6,
    width: 13.1,
    height: 11.3
  },
  {
    displayName: 'St Mary\'s Celing',
    date: '23/02/2024',
    bgColour: '#e76e50',
    textColour: 'white',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-xs',
    url: 'https://st-catharines-gdansk.vercel.app/',
    target: '_blank',
    leftShift: 51.2,
    topShift: 70.7,
    width: 9.2,
    height: 11.3
  },
  {
    displayName: 'Gdansk Street',
    date: '24/02/2024',
    bgColour: '#ee8b72',
    textColour: 'black',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-xs',
    url: 'https://gdansk-street.vercel.app/',
    target: '_blank',
    leftShift: 60.6,
    topShift: 71,
    width: 11.7,
    height: 11
  },
  {
    displayName: 'This',
    date: '25/02/2024',
    bgColour: '#f4a794',
    textColour: 'black',
    textSize: 'text-[0.3rem] sm:text-[0.5rem] md:text-xs lg:text-xs',
    url: '/',
    target: '_self',
    leftShift: 72.5,
    topShift: 71.3,
    width: 14.8,
    height: 10.5
  },
]